### ISSUE TITLE
RestoreController.CopyOnlyFileAttributesで予期しない例外が発生する

### ISSUE THREAD

**Issue by Skyzi000** [Skyzi000/SkyziBackup#65]
```
System.ArgumentException: Invalid File or Directory attributes value. (Parameter 'attributes')
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at SkyziBackup.RestoreController.CopyOnlyFileAttributes() Void SetAttributes(System.String, System.IO.FileAttributes)
```
とのこと

**Comment by Skyzi000** [comment]
とりあえず、プレビュー機能なので優先度は低い
